// worklenz-frontend/src/app/administrator/projects/project-insights/project-insights/status-overview/status-overview.component.ts
import {
  ChangeDetectionStrategy, ChangeDetectorRef,
  Component,
  Input,
  OnChanges,
  SimpleChanges,
  ViewChild
} from '@angular/core';
import {ProjectInsightsService} from "@api/project-insights.service";
import {log_error} from "@shared/utils";
import {ActivatedRoute} from "@angular/router";
import {BaseChartDirective} from "ng2-charts";
import {ChartConfiguration} from "chart.js";

declare let require: any;

@Component({
  selector: 'worklenz-status-overview',
  templateUrl: './status-overview.component.html',
  styleUrls: ['./status-overview.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class StatusOverviewComponent implements OnChanges {
  @Input() archived = false;

  @ViewChild(BaseChartDirective) chart: BaseChartDirective | undefined;
  private readonly includeArchivedTasks = "include-archived-tasks";

  loading = false;
  isChartEmpty = false;

  projectId = '';
  statusCounts: any = [];
  options: any = {};
  statusColors: string[] = [];

  chartPlugins = [];

  chartData: ChartConfiguration<'doughnut'>['data'] = {
    labels: [],
    datasets: [{
      label: 'Tasks',
      data: [],
      backgroundColor: this.statusColors,
      hoverOffset: 2
    }]
  };

  chartOptions: ChartConfiguration<'doughnut'>['options'] = {
    plugins: {
      datalabels: {
        display: false
      }
    },
    responsive: false,
  }

  constructor(
    private api: ProjectInsightsService,
    private route: ActivatedRoute,
    private readonly cdr: ChangeDetectorRef,
  ) {
    this.projectId = this.route.snapshot.paramMap.get('id') || '';
  }

  get chartWidth() {
    const windowWidth = window.innerWidth;
    if (windowWidth > 1400) {
      return 350;
    } else if (windowWidth < 1400 && windowWidth > 1200) {
      return 275;
    }
    return 220;
  }

  ngOnChanges(changes: SimpleChanges) {
    this.getStatusCounts()
  }

  get archivedTasksChoice() {
    return localStorage.getItem(this.includeArchivedTasks) === 'true';
  }

  async getStatusCounts() {
    try {
      this.loading = true;
      this.chartData.datasets[0].data = [];
      this.chartData.labels = [];
      const res = await this.api.getTaskStatusCounts(this.projectId, this.archivedTasksChoice);
      if (res.done) {
        this.statusCounts = res.body;
        await this.loadChart(this.statusCounts);
      }
      this.loading = false;
      this.cdr.markForCheck();
    } catch (e) {
      this.loading = false;
      log_error(e);
      this.cdr.markForCheck();
    }
  }

  async loadChart(seriesData: any) {
    this.chartData.datasets[0].data = [];
    this.chartData.labels = [];

    for (const item of seriesData) {
      this.chartData.labels?.push(item.name);
      this.chartData.datasets[0].data.push(item.y || 0);
      this.statusColors.push(item.color);
    }
    this.chart?.update();

    if (this.chartData.datasets[0].data.every(value => value === 0))
      this.isChartEmpty = true;

    this.cdr.markForCheck();
  }

}

<nz-spin *ngIf="loading"></nz-spin>
<!--<div #statusOverviewChart></div>-->

<div *ngIf="!isChartEmpty" class="d-flex p-3">
  <div class="position-relative" style="max-width: 350px">
    <canvas *ngIf="!isChartEmpty" baseChart
            [width]="chartWidth"
            [height]="300"
            [data]="chartData"
            [options]="chartOptions"
            [plugins]="chartPlugins"
            [legend]="false"
            [type]="'doughnut'">
    </canvas>
  </div>
  <div class="chart-details ms-3">
    <ul class="ps-0">
      <li *ngFor="let item of statusCounts"
          class="border-bottom-0 status-list list-unstyled mb-2 d-flex align-items-center">
        <nz-badge [nzColor]="item.color"></nz-badge>
        <p nz-typography class="mb-0" nz-tooltip [nzTooltipTitle]="item.name">{{item.name | ellipsis : 20}} ({{item.y}})</p>
      </li>
    </ul>
  </div>
</div>


<ng-container *ngIf="isChartEmpty">
  <div class="pt-4 pb-5 text-center">
    <div class="no-data-img-holder mx-auto mb-3">
      <img src="/assets/images/empty-box.webp" class="img-fluid" alt="">
    </div>
    <span nz-typography class="no-data-text">No tasks to show.</span>
  </div>
</ng-container>

// worklenz-frontend/src/pages/projects/projectView/insights/insights-overview/graphs/status-overview.tsx
import React, { useEffect, useState } from 'react';
import { Doughnut } from 'react-chartjs-2';
import { Chart, ArcElement } from 'chart.js';
import { Badge, Flex, Tooltip, Typography, Spin } from '@/shared/antd-imports';
import { ChartOptions } from 'chart.js';
import { projectInsightsApiService } from '@/api/projects/insights/project-insights.api.service';
import { ITaskStatusCounts } from '@/types/project/project-insights.types';
import { useAppSelector } from '@/hooks/useAppSelector';

Chart.register(ArcElement);

const StatusOverview = () => {
  const { includeArchivedTasks, projectId } = useAppSelector(state => state.projectInsightsReducer);

  const [stats, setStats] = useState<ITaskStatusCounts[]>([]);
  const [loading, setLoading] = useState(false);
  const { refreshTimestamp } = useAppSelector(state => state.projectReducer);

  const getTaskStatusCounts = async () => {
    if (!projectId) return;

    setLoading(true);
    try {
      const res = await projectInsightsApiService.getTaskStatusCounts(
        projectId,
        includeArchivedTasks
      );
      if (res.done) {
        setStats(res.body);
      }
    } catch (error) {
      console.error('Error fetching task status counts:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    getTaskStatusCounts();
  }, [projectId, includeArchivedTasks, refreshTimestamp]);

  const options: ChartOptions<'doughnut'> = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      datalabels: {
        display: false,
      },
      legend: {
        display: false,
      },
      tooltip: {
        callbacks: {
          label: context => {
            const value = context.raw as number;
            return `${context.label}: ${value} task${value !== 1 ? 's' : ''}`;
          },
        },
      },
    },
  };

  const data = {
    labels: stats.map(status => status.name),
    datasets: [
      {
        label: 'Tasks',
        data: stats.map(status => status.y),
        backgroundColor: stats.map(status => status.color),
        hoverBackgroundColor: stats.map(status => status.color + '90'),
        borderWidth: 1,
      },
    ],
  };

  if (loading) {
    return (
      <Flex justify="center" align="center" style={{ height: 350 }}>
        <Spin size="large" />
      </Flex>
    );
  }

  return (
    <Flex gap={24} wrap="wrap-reverse" justify="center">
      {loading && <Spin />}
      <div style={{ position: 'relative', height: 350, width: '100%', maxWidth: 350 }}>
        <Doughnut options={options} data={data} />
      </div>

      <Flex gap={12} style={{ marginBlockStart: 12 }} wrap="wrap" className="flex-row xl:flex-col">
        {stats.map(status => (
          <Flex key={status.name} gap={8} align="center">
            <Badge color={status.color} />
            <Typography.Text>
              {status.name}
              <span style={{ marginLeft: 4 }}>({status.y})</span>
            </Typography.Text>
          </Flex>
        ))}
      </Flex>
    </Flex>
  );
};

export default StatusOverview;
