// worklenz-frontend/src/pages/projects/projectView/insights/member-stats/member-stats.tsx
import ProjectStatsCard from '@/components/projects/project-stats-card';
import { Flex } from '@/components/ui';
import groupIcon from '@/assets/icons/insightsIcons/group.png';
import warningIcon from '@/assets/icons/insightsIcons/warning.png';
import unassignedIcon from '@/assets/icons/insightsIcons/block-user.png';
import { useEffect, useState } from 'react';
import { projectInsightsApiService } from '@/api/projects/insights/project-insights.api.service';
import { IProjectMemberStats } from '@/types/project/project-insights.types';
import logger from '@/utils/error-logger';
import { useAppSelector } from '@/hooks/use-app-selector';

const MemberStats = () => {
  const { includeArchivedTasks, projectId } = useAppSelector(state => state.projectInsightsReducer);

  const [memberStats, setMemberStats] = useState<IProjectMemberStats | null>(null);
  const [loadingStats, setLoadingStats] = useState(false);
  const { refreshTimestamp } = useAppSelector(state => state.projectReducer);

  const fetchMemberStats = async () => {
    setLoadingStats(true);
    try {
      const res = await projectInsightsApiService.getMemberInsightAStats(
        projectId,
        includeArchivedTasks
      );
      if (res.done) {
        setMemberStats(res.body);
      }
    } catch (error) {
      logger.error('Error fetching member stats:', error);
    } finally {
      setLoadingStats(false);
    }
  };

  useEffect(() => {
    fetchMemberStats();
  }, [projectId, includeArchivedTasks,refreshTimestamp]);

  return (
    <Flex gap={24} className="grid sm:grid-cols-2 sm:grid-rows-2 lg:grid-cols-3 lg:grid-rows-1">
      <ProjectStatsCard
        icon={groupIcon}
        title="Project Members"
        children={memberStats?.total_members_count}
        loading={loadingStats}
      />
      <ProjectStatsCard
        icon={warningIcon}
        title="Assignees with overdue tasks"
        children={memberStats?.overdue_members}
        loading={loadingStats}
      />
      <ProjectStatsCard
        icon={unassignedIcon}
        title="Unassigned Members"
        children={memberStats?.unassigned_members}
        loading={loadingStats}
      />
    </Flex>
  );
};

export default MemberStats;

// worklenz-frontend/src/app/administrator/projects/project-insights/project-members/member-stats/member-stats.component.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  Input,
  OnChanges,
  OnInit,
  SimpleChanges
} from '@angular/core';
import {ProjectInsightsService} from "@api/project-insights.service";
import {IProjectMemberStats} from "@interfaces/api-models/project-insights";
import {ActivatedRoute} from "@angular/router";

@Component({
  selector: 'worklenz-member-stats',
  templateUrl: './member-stats.component.html',
  styleUrls: ['./member-stats.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class MemberStatsComponent implements OnInit, OnChanges {
  @Input() archived = false;

  private readonly includeArchivedTasks = "include-archived-tasks";

  memberStats: IProjectMemberStats = {};
  projectId: string = '';

  loading = true;

  constructor(
    private api: ProjectInsightsService,
    private route: ActivatedRoute,
    private readonly cdr: ChangeDetectorRef
  ) {
    this.projectId = this.route.snapshot.paramMap.get('id') || '';
  }

  ngOnInit() {
    // void this.getProjectMemberInsights();
  }

  ngOnChanges(changes: SimpleChanges) {
    this.getProjectMemberInsights();
  }

  get archivedTasksChoice() {
    return localStorage.getItem(this.includeArchivedTasks) === 'true';
  }

  async getProjectMemberInsights() {
    try {
      this.loading = true;
      const res = await this.api.getMemberInsightAStats(this.projectId, this.archivedTasksChoice);
      if (res.done) {
        this.memberStats = res.body;
      }
      this.loading = false;
      this.cdr.markForCheck();
    } catch (e) {
      this.loading = false;
      this.cdr.markForCheck();
    }
  }
}

<nz-row [nzGutter]="16" class="mt-3 justify-content-between">
  <nz-col [nzSpan]="8">
    <nz-card class="h-100">
      <nz-skeleton [nzLoading]="loading" [nzActive]="true" [nzTitle]="false" [nzParagraph]="{ rows: 2 }"
                   [nzAvatar]="{ size: 'large', shape: 'square' }"></nz-skeleton>
      <nz-row *ngIf="!loading" [nzGutter]="16">
        <nz-col [nzSpan]="6" class="d-flex justify-content-center align-items-center">
          <div class="icon-img-holder">
            <img src="/assets/images/group.png" alt="" class="img-fluid">
          </div>
        </nz-col>
        <nz-col [nzSpan]="18">
          <h5 class="m-0 fw-normal" nz-typography>Project Members</h5>
          <h2 class="m-0" nz-typography>{{memberStats.total_members_count}}</h2>
        </nz-col>
      </nz-row>
    </nz-card>
  </nz-col>
  <nz-col [nzSpan]="8">
    <nz-card class="h-100">
      <nz-skeleton [nzLoading]="loading" [nzActive]="true" [nzTitle]="false" [nzParagraph]="{ rows: 2 }"
                   [nzAvatar]="{ size: 'large', shape: 'square' }"></nz-skeleton>
      <nz-row *ngIf="!loading" [nzGutter]="16">
        <nz-col [nzSpan]="6" class="d-flex justify-content-center align-items-center">
          <div class="icon-img-holder">
            <img src="/assets/images/warning.png" alt="" class="img-fluid">
          </div>
          <!-- <span nz-icon nzType="alert" nzTheme="outline" class="fs-50" style="color: #ff7875"></span> -->
        </nz-col>
        <nz-col [nzSpan]="18">
          <h5 class="m-0 fw-normal" nz-typography>Assignees with overdue tasks</h5>
          <h2 class="m-0" nz-typography>{{memberStats.overdue_members}}</h2>
        </nz-col>
      </nz-row>
    </nz-card>
  </nz-col>
  <nz-col [nzSpan]="8">
    <nz-card class="h-100">
      <nz-skeleton [nzLoading]="loading" [nzActive]="true" [nzTitle]="false" [nzParagraph]="{ rows: 2 }"
                   [nzAvatar]="{ size: 'large', shape: 'square' }"></nz-skeleton>
      <nz-row *ngIf="!loading" [nzGutter]="16">
        <nz-col [nzSpan]="6" class="d-flex justify-content-center align-items-center">
          <div class="icon-img-holder">
            <img src="/assets/images/block-user.png" alt="" class="img-fluid">
          </div>
        </nz-col>
        <nz-col [nzSpan]="18">
          <h5 class="m-0 fw-normal" nz-typography>Unassigned Members</h5>
          <h2 class="m-0" nz-typography>{{memberStats.unassigned_members}}</h2>
        </nz-col>
      </nz-row>
    </nz-card>
  </nz-col>
</nz-row>
